import type { InvoiceData } from "./invoice-store";

export const mockInvoiceData: InvoiceData = {
  templateId: "technology-template",
  documentType: "invoice",
  invoiceNumber: "INV-20260427-1001",
  issueDate: "2026-04-27",
  dueDate: "2026-05-11",
  currency: "USD",
  brandColor: "#2563EB",
  fromName: "Digital Invoice Agency",
  fromAddress: "451 E College Ave, New York, NY 10001",
  fromEmail: "hello@digitalinvoice.com",
  fromPhone: "+1 203 547 6458",
  fromTaxId: "TAX-30214",
  toName: "Jordan Smith",
  toAddress: "34 Court Rd, Dallas, TX 41120",
  toEmail: "jordan@email.com",
  toPhone: "+1 304 338 2788",
  toTaxId: "CUST-9921",
  items: [
    { id: "1", description: "Website UI/UX Design", quantity: 1, rate: 450 },
    { id: "2", description: "Frontend Development Sprint", quantity: 2, rate: 550 },
    { id: "3", description: "Deployment and QA", quantity: 1, rate: 300 },
  ],
  taxMode: "percent",
  taxValue: 5,
  discountMode: "flat",
  discountValue: 50,
  shippingValue: 0,
  amountPaid: 400,
  notes: "Thanks for your business.",
  terms: "Payment due within 14 days.",
  paymentInstructions: "Bank: Demo Bank\nIBAN: PK00DEMO00011223344\nSWIFT: DEMOPKKA",
} as unknown as InvoiceData;
